env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  $: readonly
  ace: readonly
  bootbox: readonly
  Blockly: writable
  Chartist: readonly
  colorPalette: writable
  goog: readonly
  Atomics: readonly
  SharedArrayBuffer: readonly
  baudrate: writable
  profile: readonly
  projectData: writable
parserOptions:
  ecmaVersion: 6
  sourceType: script
rules: {}
