name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v2
      - name: Install package node-pre-gyp
      - run: sudo apt-get update -y
        shell: bash
      - run: sudo apt-get install -y node-pre-gyp
        shell: bash
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
